// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIJg37VicvDzJPAkyPiPeDbjQc4iPVXQA',
    appId: '1:1066202636907:web:db19f4044a71cb1509c72e',
    messagingSenderId: '1066202636907',
    projectId: 'subsocials',
    authDomain: 'subsocials.firebaseapp.com',
    storageBucket: 'subsocials.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrBqrmnYhQa8TPSJTsqJPdnfrSVlyGaoM',
    appId: '1:1066202636907:android:f37b04ca646a7a6509c72e',
    messagingSenderId: '1066202636907',
    projectId: 'subsocials',
    storageBucket: 'subsocials.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQf1tOTmuME0S9iprBCSAGRL2GW2F0oK0',
    appId: '1:1066202636907:ios:0195aff67515430809c72e',
    messagingSenderId: '1066202636907',
    projectId: 'subsocials',
    storageBucket: 'subsocials.appspot.com',
    iosClientId:
        '1066202636907-f2a9l7tpefou9is2f95ego4minr6t8mj.apps.googleusercontent.com',
    iosBundleId: 'com.example.subsocial',
  );
}
